// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rental.Data.Context;

#nullable disable

namespace Rental.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Rental.Data.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Passport")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Пётр",
                            LastName = "Иванов",
                            Passport = "4010 123456",
                            Phone = "+7 (900) 111-22-33"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Анна",
                            LastName = "Петрова",
                            Passport = "4010 234567",
                            Phone = "+7 (900) 222-33-44"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Олег",
                            LastName = "Сидоров",
                            Passport = "4010 345678",
                            Phone = "+7 (900) 333-44-55"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Мария",
                            LastName = "Козлова",
                            Passport = "4010 456789",
                            Phone = "+7 (900) 444-55-66"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Дмитрий",
                            LastName = "Новиков",
                            Passport = "4010 567890",
                            Phone = "+7 (900) 555-66-77"
                        });
                });

            modelBuilder.Entity("Rental.Data.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Deposit")
                        .HasColumnType("TEXT");

                    b.Property<string>("InventoryNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InventoryNumber")
                        .IsUnique();

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Велосипеды",
                            Deposit = 3000m,
                            InventoryNumber = "INV-001",
                            Name = "Горный велосипед",
                            PricePerDay = 800m,
                            PricePerHour = 150m,
                            Status = "Свободен"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Лыжи",
                            Deposit = 5000m,
                            InventoryNumber = "INV-002",
                            Name = "Горные лыжи",
                            PricePerDay = 1000m,
                            PricePerHour = 200m,
                            Status = "Свободен"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Сноуборды",
                            Deposit = 4500m,
                            InventoryNumber = "INV-003",
                            Name = "Сноуборд",
                            PricePerDay = 900m,
                            PricePerHour = 180m,
                            Status = "В аренде"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Кемпинг",
                            Deposit = 2000m,
                            InventoryNumber = "INV-004",
                            Name = "Палатка 4-местная",
                            PricePerDay = 600m,
                            PricePerHour = 100m,
                            Status = "Свободен"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Водный спорт",
                            Deposit = 6000m,
                            InventoryNumber = "INV-005",
                            Name = "Каяк двухместный",
                            PricePerDay = 1200m,
                            PricePerHour = 250m,
                            Status = "В аренде"
                        });
                });

            modelBuilder.Entity("Rental.Data.Models.RentalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActualReturnDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DepositAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Fine")
                        .HasColumnType("TEXT");

                    b.Property<int>("InventoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlannedReturnDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tariff")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("InventoryId");

                    b.ToTable("RentalRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            DepositAmount = 6000m,
                            Fine = 0m,
                            InventoryId = 5,
                            IssueDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlannedReturnDate = new DateTime(2025, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Активна",
                            Tariff = "День",
                            TotalAmount = 0m
                        },
                        new
                        {
                            Id = 2,
                            ActualReturnDate = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = 2,
                            DepositAmount = 3000m,
                            Fine = 400m,
                            InventoryId = 1,
                            IssueDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlannedReturnDate = new DateTime(2025, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Завершена",
                            Tariff = "День",
                            TotalAmount = 2400m
                        },
                        new
                        {
                            Id = 3,
                            ActualReturnDate = new DateTime(2025, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = 3,
                            DepositAmount = 5000m,
                            Fine = 600m,
                            InventoryId = 2,
                            IssueDate = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlannedReturnDate = new DateTime(2025, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Завершена",
                            Tariff = "Час",
                            TotalAmount = 1200m
                        },
                        new
                        {
                            Id = 4,
                            ClientId = 4,
                            DepositAmount = 4500m,
                            Fine = 0m,
                            InventoryId = 3,
                            IssueDate = new DateTime(2025, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlannedReturnDate = new DateTime(2025, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Активна",
                            Tariff = "День",
                            TotalAmount = 0m
                        },
                        new
                        {
                            Id = 5,
                            ActualReturnDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = 5,
                            DepositAmount = 2000m,
                            Fine = 0m,
                            InventoryId = 4,
                            IssueDate = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlannedReturnDate = new DateTime(2025, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Завершена",
                            Tariff = "День",
                            TotalAmount = 3000m
                        });
                });

            modelBuilder.Entity("Rental.Data.Models.RentalRecord", b =>
                {
                    b.HasOne("Rental.Data.Models.Client", "Client")
                        .WithMany("Rentals")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Rental.Data.Models.Inventory", "Inventory")
                        .WithMany("Rentals")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("Rental.Data.Models.Client", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("Rental.Data.Models.Inventory", b =>
                {
                    b.Navigation("Rentals");
                });
#pragma warning restore 612, 618
        }
    }
}
